require('dotenv').config();

module.exports = {
  development: {
    username: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_NAME,
    host: process.env.DB_HOST,
    port: process.env.DB_PORT || 3306,
    dialect: 'mysql',
    logging: console.log,
    seederStorage: 'json',
    seederStoragePath: 'sequelizeData.json',
    seederStorageTableName: 'sequelizeData',
    migrationStorage: 'json',
    migrationStoragePath: 'sequelizeMeta.json',
    migrationStorageTableName: 'sequelizeMeta',
  },
  test: {
    username: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_NAME + '_test',
    host: process.env.DB_HOST,
    port: process.env.DB_PORT || 3306,
    dialect: 'mysql',
    logging: false,
    seederStorage: 'json',
    seederStoragePath: 'sequelizeData.json',
    seederStorageTableName: 'sequelizeData',
    migrationStorage: 'json',
    migrationStoragePath: 'sequelizeMeta.json',
    migrationStorageTableName: 'sequelizeMeta',
  },
  production: {
    username: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_NAME,
    host: process.env.DB_HOST,
    port: process.env.DB_PORT || 3306,
    dialect: 'mysql',
    logging: false,
    seederStorage: 'json',
    seederStoragePath: 'sequelizeData.json',
    seederStorageTableName: 'sequelizeData',
    migrationStorage: 'json',
    migrationStoragePath: 'sequelizeMeta.json',
    migrationStorageTableName: 'sequelizeMeta',
    pool: {
      max: 5,
      min: 0,
      acquire: 30000,
      idle: 10000,
    },
  },
};
